name: Unit tests

on:
  pull_request:
    paths-ignore:
      - "**.md"
      - "LICENCE"
      - "CODEOWNERS"
      - ".gitignore"
      - ".github/workflows/chainguard-digestabot.yaml"
      - ".github/workflows/codeql-trivy-scan.yaml"
      - ".github/workflows/dependabot-automerge.yaml"
      - ".github/workflows/deploy.yaml"
      - ".github/workflows/manual-deploy.yaml"
      - ".github/workflows/playwright.yaml"
      - ".github/dependabot.yaml"

jobs:
  vitest:
    permissions:
      contents: read
    name: Run unit tests
    uses: navikt/mob-gha-workflows/.github/workflows/vitest.yaml@main
    secrets: inherit
